<option value="Report1">РАПОРТ старших лікарів змін</option>
<option value="Report2">Інформація по запізненнях бригад на виклики</option>
<option value="Report3">Транспортування на Луцьк</option>
<option value="Report4">ГКС</option>
<option value="fatal">Смертність в присутності бригади (успішна реанімація)</option>
<option value="dtp+ns">ДТП</option>
<option value="ns">«НС» (надзвичайні стани)</option>
<option value="high_travmy">Складні травми</option>
<option value="tr_kytyzi">Травми китиці</option>
<option value="opic">Опіки/ Переохолодження</option>
<option value="travmat">Травматизм (кримінальний, виробничий)</option>
<option value="Report6">Зауваження по роботі, скарги, подяки</option>
